site_name: f1tenth project PSC2022
theme: readthedocs
site_url: https://example.com/
docs_dir: docs
extra_css:
  - custom.css
# use pages instead of nav for mkdocs versions <= 1.0
nav:
    - Home: index.md
    - Installation: installation.md
    - Simulation: simulation.md
    - Racecar: racecar.md
    - Our algorithms: algorithms.md
    - Main classes: 
      - AEB: node/AEB.md
      - Pure_pursuit: node/pure_pursuit.md
      - Range_finding: node/range_finding.md
      - Reactive_gap_follow: node/reactive_gap_follow.md
      - Speed: node/speed.md
      - Switcher: node/switcher.md
      - Switching_params: node/switching_params.md
      - Utils: node/utils.md
      - Wall_following: node/wall_following.md
      - Waypoint_logger: node/waypoint_logger.md
    - Rosbags: rosbags.md

# mkdocstring python library is for python >= 3
plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        search_depth: 2
        paths: 
          - ../


