site_name: f1tenth project PSC2022
theme: readthedocs
site_url: https://example.com/
docs_dir: docs
extra_css:
  - custom.css
# use pages instead of nav for mkdocs versions <= 1.0
nav:
    - Home: index.md
    - Installation: installation.md
    - Bringup: bringup.md
    - PurePursuit: purepursuit.md
    - Rosbags: rosbags.md
    - Main classes: 
      - AEB: AEB.md
      - utils: utils.md

# mkdocstring python library is for python >= 3
plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        search_depth: 2
        paths: 
          - ../


