site_name: f1tenth project PSC2022
theme: readthedocs
site_url: https://example.com/
docs_dir: docs
extra_css:
  - custom.css
# use pages instead of nav for mkdocs versions <= 1.0
nav:
    - Home: index.md
    - Installation: installation.md
    - Bringup: bringup.md
    - Rosbags: rosbags.md
    - Main classes: 
      - AEB: nodes/AEB.md
      - Pure_pursuit:
      - Range_finding:
      - Reactive_gap_follow:
      - Speed:
      - Switcher: 
      - Switching_params:
      - Utils: nodes/utils.md
      - Wall_following: 
      - Waypoint_logger: 

# mkdocstring python library is for python >= 3
plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        search_depth: 2
        paths: 
          - ../


